import type { NextPage } from "next";
import Head from "next/head";
import { Center, Link, Heading } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Center>
        <Heading>
          Welcome to <Link href="https://nextjs.org">Next.js!</Link>
        </Heading>
      </Center>
    </div>
  );
};

export default Home;
